main: fix panic
goware/modvendor pull request #8
Opened 2019-10-10 17:21 UTC by kevinburkemeter

Commit golang/go@1736f3a126ce0980e2584aebb35c94e8b33b1bfb added new
"explicit" lines to the vendor/modules.txt file, which cause this
program to panic. Fix the panic by skipping those new lines.

Updates golang/go#33848.

Fixes #7.

2019-10-10 17:58 UTC, bcmills requested changes

2019-10-10 17:58 UTC, bcmills commented on main.go
> +			}
This would be a bit more robust as:

```go
if strings.HasPrefix(line, "# ") {
```

2019-10-10 17:58 UTC, bcmills commented on main.go
> +				panic(fmt.Sprintf("could not parse modules.txt line %q: expected at least three words", line))
We don't guarantee not to add a line of this form in the future. Better to skip the line instead.

2019-10-28 13:14 UTC, pkieltyka commented
@kevinburkemeter thx for the PR -- would you mind making the changes based on @bcmills 's review and I'll merge? thank you

2020-03-17 11:48 UTC, pkieltyka commented
should be resolved by https://github.com/goware/modvendor/commit/69c7309340cf691a297ac139b2c2682e45da1e66

2020-03-17 11:48 UTC, closed without merging